apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"

resources:
  - clickhouse-init.yaml
  - clickhouse-svc.yaml
  - clickhouse-sealed-secret.yaml
  - clickhouse.yaml