apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
helmCharts:
  - name: argo-rollouts
    releaseName: argo-rollouts
    version: 2.37.2
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    namespace: argo-rollouts