apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-rollouts
    releaseName: argo-rollouts
    version: 2.37.2
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml