apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    version: v1.13.0
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    namespace: cert-manager