apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      kind: Application
    patch: |-
      - op: replace
        path: /spec/destination/server
        value: "https://cluster-not-set"
      - op: replace
        path: /spec/syncPolicy
        value:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true #
resources:
  - argo-rollout.yaml
  - istio.yaml
  - monitoring.yaml
  - argocd-image-updater.yaml
  - argo-workflows.yaml
  - cert-manager.yaml
  - infra-service.yaml
  - sealed-secrets.yaml