apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-rollout.yaml
  - istio.yaml
  - monitoring.yaml
  - argocd-image-updater.yaml
  - argo-workflows.yaml
  - cert-manager.yaml
  - infra-service.yaml
  - sealed-secrets.yaml