apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

namespace: istio-system

helmCharts:
  - name: istiod
    releaseName: istiod
    version: 1.28.3
    repo: https://istio-release.storage.googleapis.com/charts