apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argocd-image-updater
    releaseName: argocd-image-updater
    version: 0.9.1
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml