apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"

resources:
  - otel-collector-svc.yaml
  - otel-collector.yaml

configMapGenerator:
  - name: otel-collector-config
    files:
      - otel-collector-conf.yaml