apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      kind: Application
    patch: |-
      - op: replace
        path: /spec/destination/server
        value: "https://kubernetes.default.svc"
      - op: replace
        path: /spec/syncPolicy
        value:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
resources:
  - ./repository
  - ./app
  - ./project
  - ./namespaces

